export { FloatingNav } from "./FloatingNav/FloatingNav";
export { Hero } from "./Hero/Hero";
export { Problem } from "./Problem/Problem";
export { VSComparison } from "./VSComparison/VSComparison";
export { HowItWorks } from "./HowItWorks/HowItWorks";
export { Preview } from "./Preview/Preview";
export { Pricing } from "./Pricing/Pricing";
export { FAQ } from "./FAQ/FAQ";
export { Footer } from "./Footer/Footer";
